source "https://rubygems.org"

gem "business", "~> 1.0.0"
gem "uk_phone_numbers", "~> 0.1.0"

# Vulnerable gems for testing
gem "nokogiri", "~> 1.10.0"
gem "actionpack", "~> 5.2.0"
gem "activesupport", "~> 5.2.0"
gem "rack", "~> 2.0.6"
