# Dependency Review Configuration File
# This file configures the dependency review action behavior

# Possible values: "critical", "high", "moderate", "low"
fail-on-severity: critical

# You can only include one of these two options: `allow-licenses` and `deny-licenses`
# ([String]). Only allow these licenses (optional)
# Possible values: Any SPDX-compliant license identifiers or expressions from https://spdx.org/licenses/
allow-licenses:
  - GPL-3.0
  - BSD-3-Clause
  - MIT
  - Apache-2.0
  - ISC

# ([String]). Block the pull request on these licenses (optional)
# Possible values: Any SPDX-compliant license identifiers or expressions from https://spdx.org/licenses/
# Note: Uncomment below to use deny-licenses instead of allow-licenses
# deny-licenses:
#   - LGPL-2.0
#   - BSD-2-Clause
#   - GPL-2.0

# ([String]). Skip these GitHub Advisory Database IDs during detection (optional)
# Possible values: Any valid GitHub Advisory Database ID from https://github.com/advisories
# Example entries (replace with actual GHSA IDs if needed)
allow-ghsas:
  - GHSA-abcd-1234-5679
  - GHSA-efgh-1234-5679

# ([String]). Block pull requests that introduce vulnerabilities in the scopes that match this list (optional)
# Possible values: "development", "runtime", "unknown"
fail-on-scopes:
  - development
  - runtime

# ([String]). Comment summary type, can be "always" or "on-failure"
comment-summary-in-pr: on-failure

# ([Number]). Number of dependencies to fetch from the dependency graph (optional)
# Default: 5000
# retry-on-snapshot-warnings: true

# ([Boolean]). Enable or disable vulnerability detection
# vulnerability-check: true

# ([Boolean]). Enable or disable license detection
# license-check: true